### ISSUE TITLE
Incorrect version resolve

### ISSUE THREAD

**Issue by magne** [moonrepo/go-plugin#24]
The version resolve algorithm is wrong when using the `go` directive in the `go.mod` file. As stated in [Go Modules Reference](https://go.dev/ref/mod#go-mod-file-go), the `go` directive specifies the _minimum_ go version.

Proto insists on the _exact_ version, refusing to build a module specifying a minimum go version of 1.21 with a 1.22.2 go toolchain.

**Comment by milesj** [comment]
Hrmm this should resolve to `^1.21`, which means 1.22.2 should work. Let me double check.
